[package]
name = "tortuga-model"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
tokio = { version = "1.28.0", features = ["rt"] }

[dependencies]
async-trait = "0.1.64"
bincode = "1.3.3"
serde = { version = "1.0", features = ["derive"] }