[package]
name = "tortuga"
description = "An actor-based programming language."
version = "0.1.0"
authors = ["Miguel D. Salcedo <miguel@salcedo.cc>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/misalcedo/tortuga"
repository = "https://github.com/misalcedo/tortuga"
documentation = "https://docs.rs/tortuga/0.1.0/tortuga/"

[profile.release]
lto = true

[dependencies]
wasmer-runtime = "0.17"
uuid = { version = "0.8", features = ["v4", "v5"] }