[package]
name = "tortuga"
description = "Compiler and runtime for the Tortuga programming language."
version = "1.0.0"
authors = ["Miguel D. Salcedo <miguel@salcedo.cc>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://tortuga.salcedo.cc"
repository = "https://github.com/misalcedo/tortuga"
documentation = "https://docs.rs/tortuga"

[profile.release]
lto = true
debug = true

[dev-dependencies]
criterion = "0.4"

[target.'cfg(unix)'.dev-dependencies]
pprof = { version = "0.11", features = ["criterion", "flamegraph", "protobuf-codec"] }

[dependencies]
tokio = { version = "1.25.0", features = ["full"] }
wasmtime = "5.0.0"

[[bench]]
name = "fibonacci"
harness = false