[package]
name = "tortuga"
description = "Compiler and runtime for the Tortuga programming language."
version = "0.4.4"
authors = ["Miguel D. Salcedo <miguel@salcedo.cc>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/misalcedo/tortuga"
repository = "https://github.com/misalcedo/tortuga"
documentation = "https://docs.rs/tortuga"

[profile.release]
lto = true

[dev-dependencies]
criterion = "0.3"

[dependencies]
clap = "2.33"
log = "0.4"
nom = "7"
rustyline = "9"
thiserror = "1.0"
tracing = "0.1"
tracing-log = "0.1"
tracing-subscriber = { version = "0.3", features = ["parking_lot"] }
walkdir = "2.3"