[package]
name = "tortuga"
description = "An actor-based programming language."
version = "0.1.2"
authors = ["Miguel D. Salcedo <miguel@salcedo.cc>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/misalcedo/tortuga"
repository = "https://github.com/misalcedo/tortuga"
documentation = "https://docs.rs/tortuga"
autoexamples = false

[profile.release]
lto = true

[dependencies]
anyhow = "1.0"
uuid = { version = "0.8", features = ["serde", "v4"] }
thiserror = "1.0"
wasmtime = "0.21.0"
