[package]
name = "tortuga"
description = "Compiler and runtime for the Tortuga programming language."
version = "0.4.4"
authors = ["Miguel D. Salcedo <miguel@salcedo.cc>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/misalcedo/tortuga"
repository = "https://github.com/misalcedo/tortuga"
documentation = "https://docs.rs/tortuga"

[[bin]]
name = "tortuga"
path = "bin/main.rs"
required-features = ["cli"]

[profile.release]
lto = true

[dev-dependencies]
env_logger = "0.9"
test-log = { version = "0.2.8", features = ["trace"] }
tracing = { version = "0.1", default-features = false }
tracing-subscriber = { version = "0.3", default-features = false, features = ["env-filter", "fmt"] }

[features]
default = ["cli"]
cli = ["clap", "colored", "peg", "rustyline"]
peg = ["pest", "pest_derive"]

[dependencies]
clap = { version = "3.0.0-rc.9", features = ["derive"], optional = true }
colored = { version = "2.0.0", optional = true }
lazy_static = "1.4"
log = "0.4"
pest = { version = "2.1", optional = true }
pest_derive = { version = "2.1", optional = true }
proc-macro2 = "1.0.33"
rustyline = { version = "9", optional = true }
regex = "1"
thiserror = "1.0"
tracing = "0.1"
tracing-log = "0.1"
tracing-subscriber = { version = "0.3", features = ["parking_lot"] }
unicode-xid = "0.2"