[package]
name = "tortuga"
description = "Compiler and runtime for the Tortuga programming language."
version = "0.3.0"
authors = ["Miguel D. Salcedo <miguel@salcedo.cc>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/misalcedo/tortuga"
repository = "https://github.com/misalcedo/tortuga"
documentation = "https://docs.rs/tortuga"

[profile.release]
lto = true

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "emit_module"
harness = false

[dependencies]
anyhow = "1.0"
byteorder = "1.4.3"
clap = "2.33.3"
futures = "0.3.15"
leb128 = "0.2.4"
log = "0.4.14"
uuid = { version = "0.8", features = ["serde", "v4"] }
thiserror = "1.0"
tokio = { version = "1.8.0", features = ["full"] }
tokio-util = { version = "0.6.7", features = ["full"] }
tracing = "0.1"
tracing-futures = "0.2"
tracing-subscriber = "0.2"
serde = "1.0.126"
serde_yaml = "0.8.17"
walkdir = "2.3.2"
wasmtime = "0.28.0"
