[package]
name = "tortuga"
description = "An actor-based programming language."
version = "0.2.0"
authors = ["Miguel D. Salcedo <miguel@salcedo.cc>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/misalcedo/tortuga"
repository = "https://github.com/misalcedo/tortuga"
documentation = "https://docs.rs/tortuga"

[profile.release]
lto = true

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "single_message"
harness = false

[dependencies]
anyhow = "1.0"
byteorder = "1.4.3"
leb128 = "0.2.4"
uuid = { version = "0.8", features = ["serde", "v4"] }
thiserror = "1.0"
wasmtime = "0.28.0"
