#! /usr/bin/env bash

curl -fsSL https://deno.land/x/install/install.sh | sh
curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
deno install --allow-net --allow-read https://deno.land/std@0.152.0/http/file_server.ts
