mod data;
mod element;
mod export;
mod expression;
mod function;
mod global;
mod identifier;
mod instruction;
mod memory;
mod module;
mod offset;
mod start;
mod table;
mod text;
mod types;

pub use data::Data;
pub use element::Element;
pub use export::Export;
pub use expression::Expression;
pub use function::FunctionIndex;
pub use global::GlobalIndex;
pub use identifier::Identifier;
pub use instruction::Instruction;
pub use memory::{MemoryIndex, MemoryUse};
pub use offset::Offset;
pub use table::{TableIndex, TableUse};
pub use text::{Name, String};
pub use types::ReferenceType;
