[package]
name = "tortugac"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "tortugac"
path = "bin/main.rs"

[dependencies]
lazy_static = "1"
regex = "1"
thiserror = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3" }
