= Road block

My initial goal with tortuga was to do something I had not done before. To set out solving a problem that challenged me and was rewarding. I spent weeks recording voice notes about ideas for the project. I even created a Kanban board to help me see my progress and help me stick to it when things got difficult.

Things definitely got difficult. My first implementation of the language was in Rust. I struggled to get anything serious working, so I switched to Ruby. That mades things much easier. I was able to get a barebones language prototype working. However, I was not happy with my decision to use Ruby.

I wanted to use Rust for the project as a way to improve my programming skills. Thankfully, I had worked with nom before and since my language was simple enough, I was able to get a similar prototype working in Rust. Then, the next roadblock came. I had no idea how to generate runnable byte code.

After a few days of mulling over the topic, I remebered about WebAssembly. I did some research and was able to get a very simple WebAssembly programming running embedded inside of Rust. From there, things started to take off. Until I found out about WaPC. That project and the related WASSC are very similar to what I had in mind. I was discouraged.

I took a few days off from the project to really think about why I started doing this in the first place. I wanted to explore writing useful systems using unreliable asynchronous communication exclusively. Neither of those projects provided that. I still had a unique vision. So, here we are today continuing the work to get a usable version 0.1 of tortuga.