= Runtime

== Abstract
The goal of this document is to describe the technical details of the Tortuga runtime for version 0.1.

== Goals
. Allow actors to read a single integer in memory as input.
. Allow actors to send messages with a single integer as output.
. Allow actors to send messages to system actors.

== Creating actors
To create a child actor, a parent must use the system provided `create` function. This function takes a behavior reference (TBD) as input and returns an actor reference as a result.

== Sending messages
For an actor to send a mesage, the behavior must invoke a system provided function to send a message. This message must be for a valid destination for the given actor. The `send` system function takes a destination actor reference and a memory location for the outbound message.

== Altering behavior
An actor must always export the `receive` function as the entry point to handle a message.
To alter its behavior, an actor changes the function pointed to by an indirect function call in its `receive` function. Actor's with a single behavior can avoid the indirect function call.