name: Deploy Book to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: [ main ]
    paths:
      - 'compiler/**'
      - 'docs/**'
      - 'playground/**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy Book to Github Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Cache Cargo
        uses: Swatinem/rust-cache@v1.3.0
      - name: Build with WASM Pack
        working-directory: ./playground
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
          wasm-pack build --target web
      - name: Validate Links
        uses: reiddraper/freshlinks@v0.1.1
        with:
          glob: "**/*.md"
      - name: Install mdbook
        run: |
          curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.15/mdbook-v0.4.15-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=/tmp
          /tmp/mdbook build docs
      - name: Copy Overrides
        working-directory: ./docs
        run: cp editor.js book/editor.js
      - name: Copy WASM Pack
        run: cp -r playground/pkg docs/book/pkg
      - name: Bundle Compiler Module
        working-directory: docs/book
        run: |
          curl -fsSL https://deno.land/x/install/install.sh | sh
          "$HOME"/.deno/bin/deno bundle compiler.js compiler.js
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload only the book
          path: 'docs/book'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
