name: Build

on:
  pull_request: {}
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [linux, macos, windows]
        include:
          - build: linux
            os: ubuntu-latest
            rust: stable
          - build: macos
            os: macos-latest
            rust: stable
          - build: windows
            os: windows-latest
            rust: stable
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        run: |
          rustup update ${{ matrix.rust }} --no-self-update 
          rustup default ${{ matrix.rust }}
      - name: Build
        run: cargo build --verbose --release
      - name: Run tests
        run: cargo test --verbose --release
        env:
          RUST_BACKTRACE: 1
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: ${{ matrix.os }}-executable
          path: |
            target/release/tortuga
            target/release/tortuga.exe
          if-no-files-found: error
          retention-days: 0
