name: Build

on: [ push ]

jobs:
  build:
    name: Validate Compatibility
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [linux, beta, nightly, macos, windows]
        include:
          - build: linux
            os: ubuntu-latest
            toolchain: stable
          - build: beta
            os: ubuntu-latest
            toolchain: beta
          - build: nightly
            os: ubuntu-latest
            toolchain: nightly
          - build: macos
            os: macos-latest
            toolchain: stable
          - build: windows
            os: windows-latest
            toolchain: stable
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
      - name: Cache Cargo
        uses: Swatinem/rust-cache@v1.3.0
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --all-features
        env:
          RUST_BACKTRACE: 1
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}-${{ toolchain }}-executable
          path: |
            ./target/release/tortuga
            ./target/release/tortuga.exe
          if-no-files-found: error
          retention-days: 0
