name: Compatability

on:
  push:
    paths-ignore:
      - ".github/**"
      - "docs/**"
      - "examples/**"
  workflow_dispatch: {}

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Validate Compatibility
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        toolchain: [stable, beta, nightly]
        os: [ubuntu-latest, macos-latest, windows-latest]
        features: ["--features default", "--no-default-features", "--all-features"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true
      - name: Cache Cargo
        uses: Swatinem/rust-cache@v1.3.0
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose --release ${{ matrix.features }}
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --release ${{ matrix.features }}
        env:
          RUST_BACKTRACE: 1
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}-${{ matrix.toolchain }}-executable
          path: |
            ./target/release/tortuga
            ./target/release/tortuga.exe
          if-no-files-found: ignore
          retention-days: 0
