name: Linters

on:
  pull_request:
    paths:
      - 'tortuga-guest/**'
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/lint-guest.yml'

env:
  CRATE_NAME: tortuga-guest

jobs:
  rustfmt:
    name: Formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        run: |
          rustup update stable
          rustup default stable
          rustup component add rustfmt
          rustup component add clippy
      - name: Change Directory
        run: cd ${{ env.CRATE_NAME }}
      - name: Check Formatting
        run: cargo fmt --all -- --check
      - name: Check for idiomatic code
        run: cargo clippy --all --all-features -- -D warnings
