name: Linters

on: [ push ]

jobs:
  rustfmt:
    name: Formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Cache Cargo
        uses: Swatinem/rust-cache@v1.3.0
      - uses: actions-rs/cargo@v1
        with:
          command: fix
          args: --all-features
      - uses: actions-rs/cargo@
        with:
          command: fmt
      - name: Upload formatting and lint fixes
        run: |
          if [ -n "$(git status --porcelain)" ]
          then
            git config user.name "Upload lint fixes from CI"
            git config user.email ""
            git add .
            git commit -m "Automically fix lint failures and format code."
            git push
          fi