name: Linters

on: [ push ]

jobs:
  rustfmt:
    name: Formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Cache Cargo
        uses: Swatinem/rust-cache@v1.3.0
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: ---all -- --check
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all --all-features -- -D warnings
