name: Release

on:
  push:
    branches: [ main ]
    paths: [ 'Cargo.toml' ]
  workflow_dispatch: {}

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    name: Pulish to crates.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        run: |
          rustup update stable --no-self-update
          rustup default stable
      - name: Publish to Crates.io
        run: |
          cargo login ${{ secrets.CRATES_IO_TOKEN }}
          cargo publish
      - name: Build
        run: cargo build --release
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@latest
        with:
          name: executable
          path: |
            target/release/tortuga
            target/release/tortuga.exe
          if-no-files-found: error
          retention-days: 0
