name: Upload Artifacts

on:
  release:
    types: [created, published]
  workflow_dispatch: {}

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: Upload artifacts to release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [linux, macos, windows]
        include:
          - build: linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl
          - build: macos
            os: macos-latest
            target: x86_64-apple-darwin
          - build: windows
            os: windows-latest
            target: x86_64-pc-windows-msvc
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
      - name: Cache Cargo
        uses: Swatinem/rust-cache@v1.3.0
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --bin tortuga --release --all-features
      - name: Upload artifacts
        env:
          BUILD: ${{ matrix.build }}
          TARGET: ${{ matrix.target }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          TAG=v$(cargo metadata --no-deps --quiet | jq -r '.packages[] | select(.name == "tortuga") | .version')
          FILE=target/release/tortuga
          ASSET="tortuga-$TAG-$TARGET"

          if [ $BUILD -eq "windows" ]
          then
            FILE=$FILE.exe
            ASSET=$ASSET.zip

            7z a $ASSET $FILE
            gh release upload $TAG $ASSET --clobber
          else
            ASSET=$ASSET.tar.gz

            tar czf $ASSET $FILE
            gh release upload $TAG $ASSET --clobber
          fi