name: Release

on:
  release:
    types: [created]
  workflow_dispatch: {}

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    name: Pulish to crates.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: mdbook
      - name: Deploy GitHub Pages
        run: |
          cd docs/
          mdbook build
          git worktree add gh-pages gh-pages
          git config user.name "Deploy from CI"
          git config user.email ""
          cd gh-pages
          # Delete the ref to avoid keeping history.
          git update-ref -d refs/heads/gh-pages
          rm -rf *
          mv ../book/* .
          git add .
          git commit -m "Deploy $GITHUB_SHA to gh-pages"
          git push --force
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Cache Cargo
        uses: Swatinem/rust-cache@v1.3.0
      - name: Publish to Crates.io
        run: |
          cargo login ${{ secrets.CRATES_IO_TOKEN }}
          cargo publish
      - name: Edit release
        run: |
        TAG=${GITHUB_REF#*/tags/}
        cargo build --bin tortuga --release
        cd target/release
        hub release edit -m "" --attach tortuga $TAG