name: Release

on:
  release:
    types: [created]
  workflow_dispatch: {}

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    name: Pulish to ghcr.io, crates.io, Github Pages, and edit the release.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
      - name: Deploy GitHub Pages
        run: |
          cd docs/
          mkdir bin
          curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.15/mdbook-v0.4.15-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=bin
          bin/mdbook build
          git worktree add gh-pages gh-pages
          git config user.name "Deploy from CI"
          git config user.email ""
          cd gh-pages
          # Delete the ref to avoid keeping history.
          git update-ref -d refs/heads/gh-pages
          rm -rf *
          mv ../book/* .
          git add .
          git commit -m "Deploy $GITHUB_SHA to gh-pages"
          git push --force
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Cache Cargo
        uses: Swatinem/rust-cache@v1.3.0
      - name: Edit release
        run: |
          rustup target add x86_64-unknown-linux-musl
          rustup target add x86_64-apple-darwin
          rustup target add x86_64-pc-windows-msvc

          cargo build --bin tortuga --release --target x86_64-unknown-linux-musl
          cargo build --bin tortuga --release --target x86_64-apple-darwin
          cargo build --bin tortuga --release --target x86_64-pc-windows-msvc
          
          cd target/
          TAG="v$(x86_64-unknown-linux-musl/release/tortuga version)"
          
          hub release edit -m "" --attach x86_64-unknown-linux-musl/release/tortuga $TAG
          hub release edit -m "" --attach x86_64-apple-darwin/release/tortuga $TAG
          hub release edit -m "" --attach x86_64-pc-windows-msvc/release/tortuga.exe $TAG
      - name: Publish to Crates.io
        run: |
          cargo login ${{ secrets.CRATES_IO_TOKEN }}
          cargo publish