name: Rust - Runtime

on:
  push:
    branches: [ main ]
    paths:
      - 'tortuga-runtime/**'
      - '.github/workflows/rust-runtime.yml'
  pull_request:
    paths:
      - 'tortuga-runtime/**'

env:
  CARGO_TERM_COLOR: always
  CRATE_NAME: tortuga-runtime

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [linux, macos, windows]
        include:
          - build: linux
            os: ubuntu-latest
            rust: stable
          - build: macos
            os: macos-latest
            rust: stable
          - build: windows
            os: windows-latest
            rust: stable
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        run: |
          rustup update ${{ matrix.rust }} --no-self-update 
          rustup default ${{ matrix.rust }}
      - name: Build
        working-directory: ${{ env.CRATE_NAME }}
        run: cargo build --verbose
      - name: Run tests
        working-directory: ${{ env.CRATE_NAME }}
        run: cargo test --verbose
        env:
          RUST_BACKTRACE: 1
