name: Add Tag

on:
  push:
    branches: [ main ]

jobs:
  tag:
    name: Define Tags for version in Cargo.toml
    runs-on: ubuntu-latest
    steps:
      - name: Create or Update Tag
        run: |
          git config user.name "Add Tag from CI"
          git config user.email ""

          TAG=$(cargo metadata --no-deps --quiet | jq -r '.packages[] | select(.name == "tortuga") | .version')

          git tag "v$TAG" --force
          git push --tags --force