name: Add Tag

on:
  push:
    branches: [ main ]

jobs:
  tag:
    name: Define Tags for version in Cargo.toml
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create or Update Tag
        run: |
          git config user.name "Add Tag from CI"
          git config user.email ""

          TAG=v$(cargo metadata --no-deps --quiet | jq -r '.packages[] | select(.name == "tortuga") | .version')

          git tag $TAG --force
          git push --tags --force

          gh release view $TAG &> /dev/null
          
          if [ $? -eq 0 ]
          then
            echo "Release $TAG already exists."
          else
            echo "Creating release $TAG."
            gh release create $TAG -d --notes $TAG
          fi